Removed xmllint dependency.

diff --git a/danime/11search b/danime/11search
--- a/danime/11search
+++ b/danime/11search
@@ -53,6 +53,7 @@ da_search() {
 	fi
 	stop_spinner $?
 	if [ -z "$(echo "$RES" | tr -d '[:space:]')" ]; then
+		echo You should check your keywords.
 		return 4
 	fi
 	total_res=$(echo "$RES" | wc -l)
@@ -76,13 +77,13 @@ da_search() {
 		target=$(echo "$RES" | head -n "$n" | tail -1)
 		local base
 		base="$(set_basedir "${target%%:*}")"
-		if ! [ -d "$base" ]||! [ -e "$base" ];then
+		if ! [ -d "$base" ] || ! [ -e "$base" ]; then
 			rm -rf "$base"
 			mkdir -p "$base"
 		fi
 		cd "$base" || true
 		local dir
-		dir="$(echo "$target"|cut -d: -f2-|replace_invalid dir)"
+		dir="$(echo "$target" | cut -d: -f2- | replace_invalid dir)"
 		if [ ! -d "$dir" ]; then
 			rm -f "$dir"
 			mkdir "$dir"
@@ -96,15 +97,14 @@ da_search() {
 		fi
 	done
 }
-set_basedir()
-{
+set_basedir() {
 	case $1 in
-		anime/*) echo "$ANIME_PATH";;
-		*power-rangers*) echo "$POWER_RANGERS_PATH";;
-		*tv-series*|*kamen-rider*) echo "$TV_SERIES_PATH";;
-		*movie*) echo "$MOVIE_PATH";;
-		cartoon/*) echo	"$CARTOON_PATH";;
-	esac	
+		anime/*) echo "$ANIME_PATH" ;;
+		*power-rangers*) echo "$POWER_RANGERS_PATH" ;;
+		*tv-series* | *kamen-rider*) echo "$TV_SERIES_PATH" ;;
+		*movie*) echo "$MOVIE_PATH" ;;
+		cartoon/*) echo "$CARTOON_PATH" ;;
+	esac
 }
 #end:code
 if ! ([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] \
diff --git a/danime/13download b/danime/13download
--- a/danime/13download
+++ b/danime/13download
@@ -21,7 +21,9 @@ da_get_episede() {
 	else
 		IFS=$'\n'
 		tput sc
+		set +x
 		start_spinner "Fetching info about  episode[dubbedanime:$(echo "$1" | rev | cut -d/ -f1 | rev | cut -d- -f1)]"
+		${DEBUG:-false} && set -x
 		parse_episede_page="$(curl "$1" 2> /dev/null)"
 		episode_type=$(echo "$1" | cut -d/ -f4)
 		if [[ $tr = dubbed ]] || [[ $tr = subbed ]]; then
@@ -31,7 +33,7 @@ da_get_episede() {
 		fi
 		if [ "$episode_type" = "episode" ]; then
 
-			ep_title=$(echo "$parse_episede_page" | grep -v doctype | xmllint --html --xpath '/html/body/div[4]/div/div/div[1]/h1' - 2> /dev/null | tail -1 | tr \  \\n | head -n -1 | tr \\n \  | sed 's| $||g;s|episode|ep|gI;s|ova|ova|gI;s|ona|ona|gI;s|movie|movie|gI;s|special|special|gI')
+			ep_title=$(echo "$parse_episede_page" | grep -v doctype | sed -n "/<h1 class='dosis ep-title'>/,/<\/h1>/{/<h1 class='dosis ep-title'>/d;s| *</h1>||g;p}" | sed 's| $||g;s|episode|ep|gI;s|ova|ova|gI;s|ona|ona|gI;s|movie|movie|gI;s|special|special|gI')
 			ep_id_list=$(echo "$parse_episede_page" | sed 's|\;$||g' | grep var\ episode | cut -d= -f2 | jsonparser | grep '\[\"videos\",[[:digit:]]*\]' | tr -d '[:blank:]' | cut -d\] -f2- | grep $SUPPORTED_HOSTS | eval $filter | awk -F, '{print $1","$3","$2","$4;}')
 			if [ -z "$ep_id_list" ]; then
 				tr=subbed
@@ -43,6 +45,7 @@ da_get_episede() {
 			ep_id_list=$(echo "$parse_episede_page" | sed 's|\;$||g' | grep var\ episode | cut -d= -f2 | jsonparser | grep '\[\"videos\",[[:digit:]]*\]' | tr -d '[:blank:]' | cut -d\] -f2- | grep $SUPPORTED_HOSTS | sort)
 			ep_file_name="$(echo "$ep_title" | replace_invalid).mp4"
 		fi
+		set +x
 		if [ -n "$parse_episede_page" ] && [ -n "$ep_title" ]; then
 			stop_spinner 0
 		else
@@ -60,10 +63,12 @@ da_get_episede() {
 		vbar
 		for n in $ep_id_list; do
 			ep_file_url=
-			$DEBUG && set -x
+			${DEBUG:-false} && set -x
 			ep_file_host=$(echo "$n" | jsonparser -b | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[host\]' | cut -d\  -f2)
 			ep_file_id=$(echo "$n" | jsonparser -b | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[id\]' | cut -d\  -f2)
+			set +x
 			start_spinner "Getting url from provider[$ep_file_host:$ep_file_id]"
+			${DEBUG:-false} && set -x
 			if [ "$(echo "$ep_id_list" | wc -l)" -eq 1 ]; then
 				while [ -z "$ep_file_url" ]; do
 					sleep 1
@@ -82,7 +87,10 @@ da_get_episede() {
 				if ((ret == 0)); then
 					download "$ep_file_name" "$ep_file_url"
 					return 0
-				elif ( ((ret == 4)) || ((ret == 5)) ) && [[ $REPLACE_ON_ERROR == "true" ]]; then
+				elif (
+					true
+					((ret == 4)) || ((ret == 5))
+				) && [[ $REPLACE_ON_ERROR == "true" ]]; then
 					rm "$ep_file_name"
 					download "$ep_file_name" "$ep_file_url"
 					return 0
@@ -106,26 +114,26 @@ download() {
 	s2=$(stat -c%s "$1" 2> /dev/null || echo 0)
 	if ((s1 >= s2)); then
 		fget "$2" "$1"
-		a=$?
+		ret=$?
 	else
 		echo "Manually downloaded $1[$(byte_hr "$s2")],skipping."
 	fi
-	if [[ $a -eq 0 ]] || ([ "$CHECK_FILE" == "false" ]); then
+	if ((ret == 0))|| ([ "$CHECK_FILE" == "false" ]); then
 		return 0
 	fi
 	start_spinner "Checking $(ellipsis 40 "$1") integrity"
-	$DEBUG && set -x
+	${DEBUG:-false} && set -x
 	if [ -n "$(ffmpeg -v error -map 0:0 -f null - -i "$1" 2>&1 | grep -v '^\[\|^[[:blank:]]')" ] || ((s1 < s2)); then
 		stop_spinner 1
 		echo "$1 is corrupted"
-		return $((a + 1))
+		return $((ret + 1))
 	else
 		stop_spinner 0
-		return $((a + $?))
+		return $((ret + $?))
 	fi
 }
 compare_episode() {
-	$DEBUG && set -x
+	${DEBUG:-false} && set -x
 	if [ ! -e "$1" ] || ([ -n "$CHECK_FILE" ] && [ "$CHECK_FILE" == "false" ]); then
 		return 0
 	elif [ "$CHECK_FILE" == "error" ]; then
@@ -144,10 +152,10 @@ compare_episode() {
 	for ((i = 0; i < ${TOTAL_CHECKS:-10}; i++)); do
 		printf "\rComparing episode[test:%d]" "$((i + 1))"
 		start=$(shuf -i 0-$((size - ${BS:-524288})) -n 1)
-		a=$(dd bs=1 count="${BS:-524288}" status=none if="$1" skip="$start" | sha256sum | cut -d\  -f1)
-		b=$(curl -kr "$start-$((start + ${BS:-524288} - 1))" "$2" 2> /dev/null | sha256sum | cut -d\  -f1)
-		test "$a" = "$b" || echo -e "\rComparing episode[test:$((i + 1)):fail]"
-		test "$a" = "$b" || return 4
+		hash1="$(dd bs=1 count="${BS:-524288}" status=none if="$1" skip="$start" | sha256sum | cut -d\  -f1)"
+		hash2="$(curl -kr "$start-$((start + ${BS:-524288} - 1))" "$2" 2> /dev/null | sha256sum | cut -d\  -f1)"
+		test "$hash1" = "$hash2" || echo -e "\rComparing episode[test:$((i + 1)):fail]"
+		test "$hash1" = "$hash2" || return 4
 	done
 	echo -e "\rComparing episode[test:1-${TOTAL_CHECKS:-10}:pass]"
 	return 0
diff --git a/danime/35footer b/danime/35footer
--- a/danime/35footer
+++ b/danime/35footer
@@ -12,7 +12,24 @@ DEBUG=${DEBUG:-false}
 if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 	while [ -n "$1" ]; do
 		case $1 in
-			-d|--debug)
+			-B[[:digit:].]*[kKmM] | --block=[[:digit:].]*[kKmM])
+				BS=${1#*=}
+				[[ $BS =~ ^[[:digit:].]+[[:digit:]kKmM]$ ]] || BS=${1/-B/}
+				BS=$(echo "$BS" | byte_mr)
+				;;
+			-B[[:digit:].]* | --block=[[:digit:].]*)
+				BS=${1#*=}
+				[[ $BS =~ ^[[:digit:].]+$ ]] || BS=${1/-B/}
+				;;
+			-B | --block)
+				BS=$2
+				if [[ $BS =~ ^[[:digit:].]+[[:digit:]kKmM]$ ]]; then
+					BS=$(echo "$BS" | byte_mr)
+				else
+					echo "Invalid block size." 1>&2
+				fi
+				;;
+			-d | --debug)
 				DEBUG=true
 				;;
 			-A)
@@ -36,11 +53,15 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				EP_LIST=true
 				EP_LIST_RANGE=${1#*=}
 				[[ $EP_LIST_RANGE =~ ^[[:digit:],-]+$ ]] || EP_LIST_RANGE=${1/-e/}
+				EP_LIST_RANGE=$(echo "$EP_LIST_RANGE" | grep -o . | grep '^[[:digit:],-]*$' | tr -d \\n | sed 's/,$//')
 				;;
 			-s | --select)
 				if [[ $2 =~ ^[[:digit:],-]+$ ]]; then
 					RES_LIST=$2
 					shift
+				else
+					echo "Invalid selection index." 1>&2
+					exit 1
 				fi
 				;;
 			-s[[:digit:],-]* | --select=[[:digit:],-]*)
