Added support to download multipart episode.

diff --git a/danime/13download b/danime/13download
--- a/danime/13download
+++ b/danime/13download
@@ -19,7 +19,8 @@ da_get_episede() {
 	if (($# == 0)); then
 		return 1
 	else
-		local IFS="$IFS" tr="$tr"
+		local IFS tr file_num
+		tr="$tr"
 		IFS=$'\n'
 		tput sc
 		set +x
@@ -64,16 +65,16 @@ da_get_episede() {
 				ep_title="${ep_title% *} $(echo "${ep_title##* } $ep_number" | sed 's| $||g;s|episode|ep|gI;s|ova|ova|gI;s|ona|ona|gI;s|movie|movie|gI;s|special|special|gI')"
 			fi
 			ep_id_list=$(
-				echo "$parse_episede_page" | sed 's|\;$||g' | grep var\ episode | cut -d= -f2 | jsonparser -q | grep '\[\"videos\",[[:digit:]]*\]' | tr -d '[:blank:]' | cut -d\] -f2- | grep $SUPPORTED_HOSTS | eval $filter | awk -F, '{print $1","$2","$3"}";}'
+				echo "$parse_episede_page" | sed 's|\;$||g' | grep var\ episode | cut -d= -f2 | jsonparser -q | grep '\[\"videos\",[[:digit:]]*\]' | tr -d '[:blank:]' | cut -d\] -f2- |sed 's|","|"\|"|g'| grep $SUPPORTED_HOSTS | eval $filter | awk -F\| '{print $1","$2","$3"}";}'|sed 's|"\|"|","|g'
 				curl "https://vid.xngine.com/api/episode/$(echo "$parse_episede_page" | grep 'var episode' | sed 's|;$||g' | cut -d= -f2 | jsonparser -b -q | grep slug | tr -s '[:blank:]' \  | cut -d\  -f2 | tr -d \")" -s 2> /dev/null | jsonparser -q | grep -E '^\[[[:digit:]]+\]' | tr -s '[:blank:]' \  | cut -d\  -f2 | grep $SUPPORTED_HOSTS | eval $filter
 			)
 
 			if [ -z "$ep_id_list" ]; then
 				tr=subbed
 				ep_id_list=$(
-					echo "$parse_episede_page" | sed 's|\;$||g' | grep var\ episode | cut -d= -f2 | jsonparser -q | grep '\[\"videos\",[[:digit:]]*\]' | tr -d '[:blank:]' | cut -d\] -f2- | grep $SUPPORTED_HOSTS | eval $filter | awk -F, '{print $1","$2","$3"}";}'
-					curl "https://vid.xngine.com/api/episode/$(echo "$parse_episede_page" | grep 'var episode' | sed 's|;$||g' | cut -d= -f2 | jsonparser -b -q | grep slug | tr -s '[:blank:]' \  | cut -d\  -f2 | tr -d \")" -s 2> /dev/null | jsonparser -q | grep -E '^\[[[:digit:]]+\]' | tr -s '[:blank:]' \  | cut -d\  -f2 | grep $SUPPORTED_HOSTS | eval $filter
-				)
+					echo "$parse_episede_page" | sed 's|\;$||g' | grep var\ episode | cut -d= -f2 | jsonparser -q | grep '\[\"videos\",[[:digit:]]*\]' | tr -d '[:blank:]' | cut -d\] -f2- |sed 's|","|"\|"|g'| grep $SUPPORTED_HOSTS | eval $filter | awk -F\| '{print $1","$2","$3"}";}'|sed 's|"\|"|","|g'
+						curl "https://vid.xngine.com/api/episode/$(echo "$parse_episede_page" | grep 'var episode' | sed 's|;$||g' | cut -d= -f2 | jsonparser -b -q | grep slug | tr -s '[:blank:]' \  | cut -d\  -f2 | tr -d \")" -s 2> /dev/null | jsonparser -q | grep -E '^\[[[:digit:]]+\]' | tr -s '[:blank:]' \  | cut -d\  -f2 | grep $SUPPORTED_HOSTS | eval $filter
+					)
 			fi
 			ep_file_name="$(echo "$ep_title" | replace_invalid)-$tr.mp4"
 		elif [ "$episode_type" = "cartoon" ]; then
@@ -118,7 +119,7 @@ da_get_episede() {
 			ep_file_host=$(echo "$n" | jsonparser -b -q | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[host\]' | cut -d\  -f2)
 			ep_file_id=$(echo "$n" | jsonparser -b -q | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[id\]' | cut -d\  -f2)
 			set +x
-			start_spinner "Getting url from provider[$ep_file_host:$ep_file_id]"
+			start_spinner "Getting url from provider[$ep_file_host:$(ellipsis 15 "$ep_file_id" )]"
 			${DEBUG:-false} && set -x
 			if [ "$(echo "$ep_id_list" | wc -l)" -eq 1 ]; then
 				while [ -z "$ep_file_url" ]; do
@@ -128,47 +129,60 @@ da_get_episede() {
 			else
 				ep_file_url=$(parse_episede_id "$n")
 			fi
-			if [[ $ep_file_url =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.mp4[[:alnum:][:punct:]]* ]]; then
-				stop_spinner 0
-				if ! ([[ $tr = dubbed ]] || [[ $tr = subbed ]]); then
-					tr=$(echo "$n" | jsonparser -b -q | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[type\]' | cut -d\  -f2)
-				fi
-				if [[ $(curl -kLsI "$ep_file_url" 2> /dev/null | grep -i '^http/' | tail -1 | cut -d\  -f2) =~ ^4[[:digit:]][[:digit:]]$ ]]; then
-					echo 404 not found.
-					continue
-				fi
-				if ${SKIP_DOWNLOAD:-false}; then
-					return 0
-				fi
-				compare_episode "$ep_file_name" "$ep_file_url"
-				ret=$?
-				if ((ret == 0)); then
-					download "$ep_file_name" "$ep_file_url"
-					return 0
-				elif (
-					((ret == 4)) \
-						&& (
-							${REPLACE_FAIL:-false} || ((${failed_tests:-0} <= 5))
-						) && ! ${NO_REPLACE:-false}
-				) || ((ret == 5)) || ( ${REPLACE_MANUAL:-false} && ((ret == 3))); then
-					#echo " overwriting"
-					rm "$ep_file_name"
-					download "$ep_file_name" "$ep_file_url"
-					return 0
-				else
-					echo -e "\nFile doesn't match."
-				fi
-			elif [[ $ep_file_url =~ unimplemented:[:alnum:]* ]]; then
-				stop_spinner 1
-				echo "URL extractor not available for ${ep_file_url##*:}"
-			elif [[ $ep_file_url =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]]; then
-				stop_spinner 1
-				echo "M3U8 downloader is not implemented." 1>&2
-				echo -e "Please run \n  \`ffmpeg -i \"$ep_file_url\" -c copy \"$PWD/$ep_file_name\"\`"
-			else
-				stop_spinner 1
-				echo "URL Parsing error"
+			if [[ $(echo "$ep_file_url"|wc -l) -gt 1 ]];then
+				file_num=0
 			fi
+			for ep_file_url_current in $ep_file_url;do
+				if [ -n "$file_num" ];then
+					file_num=$((file_num+1))
+					if [ "$episode_type" = "cartoon" ];then
+						ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num.mp4"
+					else
+						ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num-$tr.mp4"
+					fi
+				fi
+				if [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.mp4[[:alnum:][:punct:]]* ]]; then
+					stop_spinner 0
+					if ! ([[ $tr = dubbed ]] || [[ $tr = subbed ]]); then
+						tr=$(echo "$n" | jsonparser -b -q | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[type\]' | cut -d\  -f2)
+					fi
+					if [[ $(curl -kLsI "$ep_file_url_current" 2> /dev/null | grep -i '^http/' | tail -1 | cut -d\  -f2) =~ ^4[[:digit:]][[:digit:]]$ ]]; then
+						echo 404 not found.
+						continue
+					fi
+					if ${SKIP_DOWNLOAD:-false}; then
+						return 0
+					fi
+					compare_episode "$ep_file_name" "$ep_file_url_current"
+					ret=$?
+					if ((ret == 0)); then
+						download "$ep_file_name" "$ep_file_url_current"
+						return 0
+					elif (
+						((ret == 4)) \
+							&& (
+								${REPLACE_FAIL:-false} || ((${failed_tests:-0} <= 5))
+							) && ! ${NO_REPLACE:-false}
+					) || ((ret == 5)) || ( ${REPLACE_MANUAL:-false} && ((ret == 3))); then
+						#echo " overwriting"
+						rm "$ep_file_name"
+						download "$ep_file_name" "$ep_file_url_current"
+						return 0
+					else
+						echo -e "\nFile doesn't match."
+					fi
+				elif [[ $ep_file_url_current =~ unimplemented:[:alnum:]* ]]; then
+					stop_spinner 1
+					echo "URL extractor not available for ${ep_file_url_current##*:}"
+				elif [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]]; then
+					stop_spinner 1
+					echo "M3U8 downloader is not implemented." 1>&2
+					echo -e "Please run \n  \`ffmpeg -i \"$ep_file_url_current\" -c copy \"$PWD/$ep_file_name\"\`"
+				else
+					stop_spinner 1
+					echo "URL Parsing error"
+				fi
+			done
 		done
 	fi
 }
@@ -216,8 +230,16 @@ compare_episode() {
 		return 0
 	fi
 	${DEBUG:-false} && set -x
-	if ! (dd if="$1" of=/dev/null bs=1 count=1 status=none 2> /dev/null && exit "$(ffprobe -hide_banner -loglevel 16 "$1" 2>&1 | wc -l)"); then
+	if ! (dd if="$1" of=/dev/null bs=1 count=1 status=none 2> /dev/null && exit "$(ffprobe -hide_banner -loglevel 14 "$1" 2>&1 | wc -l)"); then
 		return 5
+	fi
+	if command -v mediainfo &>/dev/null;then
+		asize=$(mediainfo "$1" 2>/dev/null|tr -s '[:blank:]' \ |grep -i 'stream size'|sed 's|: |:|g'|cut -d: -f2|cut -d\  -f1|awk '{printf $0"*1048576+"};END {printf "0\n"}'|bc|cut -d\. -f1)
+	else
+		asize=$size
+	fi
+	if ((asize>wsize));then
+		return 3
 	fi
 	${DEBUG:-false} && set +x
 	failed_tests=${TOTAL_CHECKS:-10}
