Added multipart episode support.

diff --git a/danime/13download b/danime/13download
--- a/danime/13download
+++ b/danime/13download
@@ -19,7 +19,7 @@ da_get_episede() {
 	if (($# == 0)); then
 		return 1
 	else
-		local IFS tr file_num
+		local IFS tr file_num ret dlret
 		tr="$tr"
 		IFS=$'\n'
 		tput sc
@@ -132,17 +132,17 @@ da_get_episede() {
 			if [[ $(echo "$ep_file_url"|wc -l) -gt 1 ]];then
 				file_num=0
 			fi
-			for ep_file_url_current in $ep_file_url;do
-				if [ -n "$file_num" ];then
-					file_num=$((file_num+1))
-					if [ "$episode_type" = "cartoon" ];then
-						ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num.mp4"
-					else
-						ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num-$tr.mp4"
+			if [[ $ep_file_url =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.mp4[[:alnum:][:punct:]]* ]]; then
+				stop_spinner 0
+				for ep_file_url_current in $ep_file_url;do
+					if [ -n "$file_num" ];then
+						file_num=$((file_num+1))
+						if [ "$episode_type" = "cartoon" ];then
+							ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num.mp4"
+						else
+							ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num-$tr.mp4"
+						fi
 					fi
-				fi
-				if [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.mp4[[:alnum:][:punct:]]* ]]; then
-					stop_spinner 0
 					if ! ([[ $tr = dubbed ]] || [[ $tr = subbed ]]); then
 						tr=$(echo "$n" | jsonparser -b -q | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[type\]' | cut -d\  -f2)
 					fi
@@ -151,13 +151,12 @@ da_get_episede() {
 						continue
 					fi
 					if ${SKIP_DOWNLOAD:-false}; then
-						return 0
+						continue
 					fi
 					compare_episode "$ep_file_name" "$ep_file_url_current"
 					ret=$?
 					if ((ret == 0)); then
 						download "$ep_file_name" "$ep_file_url_current"
-						return 0
 					elif (
 						((ret == 4)) \
 							&& (
@@ -167,22 +166,22 @@ da_get_episede() {
 						#echo " overwriting"
 						rm "$ep_file_name"
 						download "$ep_file_name" "$ep_file_url_current"
-						return 0
 					else
 						echo -e "\nFile doesn't match."
 					fi
-				elif [[ $ep_file_url_current =~ unimplemented:[:alnum:]* ]]; then
-					stop_spinner 1
-					echo "URL extractor not available for ${ep_file_url_current##*:}"
-				elif [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]]; then
-					stop_spinner 1
-					echo "M3U8 downloader is not implemented." 1>&2
-					echo -e "Please run \n  \`ffmpeg -i \"$ep_file_url_current\" -c copy \"$PWD/$ep_file_name\"\`"
-				else
-					stop_spinner 1
-					echo "URL Parsing error"
-				fi
-			done
+				done
+				break
+			elif [[ $ep_file_url_current =~ unimplemented:[:alnum:]* ]]; then
+				stop_spinner 1
+				echo "URL extractor not available for ${ep_file_url##*:}"
+			elif [[ $ep_file_url =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]]; then
+				stop_spinner 1
+				echo "M3U8 downloader is not implemented." 1>&2
+				echo -e "Please run \n  \`ffmpeg -i \"$ep_file_url_current\" -c copy \"$PWD/$ep_file_name\"\`"
+			else
+				stop_spinner 1
+				echo "URL Parsing error"
+			fi
 		done
 	fi
 }
