Some fixes.
 * Show error for mp4upload missing url.
 * Replaced $ANIME_ROOT with $MEDIA_ROOT
 * convert localized numbers to english.
 * fix episode list expansion
 * show total download progress.
 * bit touches here and there.

diff --git a/danime/13download b/danime/13download
--- a/danime/13download
+++ b/danime/13download
@@ -20,7 +20,9 @@ da_get_episede() {
 	if (($# == 0)); then
 		return 1
 	else
-		local IFS file_num ret dlret
+		local IFS file_num ret progress total_pw
+		progress=$4
+		total_pw=$5
 		local tr="$tr"
 		IFS=$'\n'
 		tput sc
@@ -40,7 +42,7 @@ da_get_episede() {
 			tr=dubbed
 		fi
 		if [[ $tr = dubbed ]] || [[ $tr = subbed ]]; then
-			filter='grep \"type\":\"$tr'
+			filter="grep '\"type\":\"$tr'"
 		else
 			filter="cat"
 		fi
@@ -110,7 +112,7 @@ da_get_episede() {
 		tput rc
 		vbar
 		vbar "$ep_title" true
-		vbar "ID:$(echo "$1" | rev | cut -d/ -f1 | rev | cut -d- -f1)"
+		vbar "ID:$(echo "$1" | rev | cut -d/ -f1 | rev | cut -d- -f1)$([ -n "$progress" ] && [ -n "$total_pw" ] && echo " - Progress:$progress/$total_pw")"
 		vbar
 		if [ "$(echo "$ep_id_list" | wc -l)" -eq 1 ] && [ -z "$REPLACE_FAIL" ]; then
 			REPLACE_FAIL=true
@@ -137,28 +139,28 @@ da_get_episede() {
 				ep_file_url=$(parse_episede_id "$n")
 			fi
 			for ep_file_url_current in $ep_file_url; do
-				if ! remote_exist "$ep_file_url_current"; then
+				if [[ $ep_file_url_current =~ error:* ]]; then
 					ep_file_url=
 					stop_spinner 1
-					echo "404 Error on this mirror."
-					continue 2
-				elif [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.mp4[[:alnum:][:punct:]]* ]]; then
+					echo "[Error] ${ep_file_url_current#*:}"
 					continue
 				elif [[ $ep_file_url_current =~ unimplemented:[:alnum:]* ]]; then
 					ep_file_url=
 					stop_spinner 1
-					echo "URL extractor not available for ${ep_file_url##*:}"
+					echo "[Error] URL extractor not implemented for ${ep_file_url##*:}"
 					continue 2
 				elif [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]]; then
 					ep_file_url=
 					stop_spinner 1
-					echo "M3U8 downloader is not implemented." 1>&2
+					echo "[Warn] HLS video downloader is not implemented." 1>&2
 					echo -e "Please run \n  \`ffmpeg -i \"$ep_file_url_current\" -c copy \"$PWD/$ep_file_name\"\`"
 					continue 2
+				elif remote_exist "$ep_file_url_current"; then
+					continue
 				else
 					ep_file_url=
 					stop_spinner 1
-					echo "URL Parsing error"
+					echo "[Error] 404 not found."
 					continue 2
 				fi
 			done
diff --git a/danime/14parse b/danime/14parse
--- a/danime/14parse
+++ b/danime/14parse
@@ -15,7 +15,7 @@ parse_episede_id() {
 		if [ -n "$(type -t get_url_$ep_file_host)" ]; then
 			get_url_$ep_file_host "$n" 2> /dev/null
 		else
-			echo unimplemented:${ep_file_host/_/.}
+			echo "unimplemented:${ep_file_host/_/.}"
 			break
 		fi
 	done
@@ -23,6 +23,9 @@ parse_episede_id() {
 
 get_url_mp4upload() {
 	curl "https://www.mp4upload.com/embed-$1.html" 2> /dev/null | grep 'eval(' | cut -d\> -f2- | js-beautify -xn -e \\n -k --brace-style=expand | tr -d \",\ \)\; |grep '^player\.src'|cut -d\( -f2-
+	if [ "${PIPESTATUS[1]}" = "1" ];then
+		echo "error:File is deleted."
+	fi
 }
 get_url_trollvid() {
 	curl -H 'range: bytes=0-' -H 'referer: https://localhost/' -w '%{redirect_url}' "$(curl -H 'accept-encoding: identity' -H 'referer: https://localhost/' "https://mp4.sh/embed/$1" --output - 2> /dev/null | grep source | tr -d \" | tr \  \\n | grep '^src' | cut -d= -f2-)" 2> /dev/null | grep '^http' | cat
@@ -33,7 +36,7 @@ get_url_mp4_sh() {
     if ! echo "$url" | grep -q 'st=.*e=.*';then
 	    curl -H 'range: bytes=0-' -H 'referer: https://localhost/' -w '%{redirect_url}' "" 2> /dev/null | grep '^http' | cat
 	else
-	    echo $url
+	    echo "$url"
 	fi
 }
 
@@ -41,4 +44,3 @@ get_url_vidstreaming() {
 	curl -s "https://vidstreaming.io/download?id=$1" |grep 'http'|grep 'download'|tr -d '[:blank:]'|cut -d\" -f2|sed 's|amp\;||g'|tail -2|head -1
 }
 #end:code
-
diff --git a/danime/35footer b/danime/35footer
--- a/danime/35footer
+++ b/danime/35footer
@@ -7,7 +7,6 @@
 . 13download
 . 14parse
 DEBUG=${DEBUG:-false}
-# shellcheck disable=SC2086
 #start:code
 if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 	while [ -n "$1" ]; do
@@ -89,7 +88,7 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				;;
 			-r | --replace)
 				if echo "$2" | grep -q 'manual\|fail'; then
-					eval "REPLACE_$(echo $2 | tr '[:lower:]' '[:upper:]')=true"
+					eval "REPLACE_$(echo "$2" | tr '[:lower:]' '[:upper:]')=true"
 					shift
 				else
 					REPLACE_FAIL=true
@@ -97,8 +96,8 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				fi
 				;;
 			-r[fm] | --replace=fail | --replace=manual)
-				REPLACE="$(echo ${1#*=} | tr '[:lower:]' '[:upper:]')"
-				if ! echo $REPLACE | grep -qi 'manual\|fail'; then
+				REPLACE="$(echo "${1#*=}" | tr '[:lower:]' '[:upper:]')"
+				if ! echo "$REPLACE" | grep -qi 'manual\|fail'; then
 					REPLACE="$(
 						if [ "${1/-r/}" = "m" ]; then
 							echo manual
@@ -112,14 +111,15 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				;;
 			-e | --ep-list)
 				EP_LIST=true
-				if [[ $2 =~ ^[[:digit:],-]+$ ]]; then
-					EP_LIST_RANGE=$2
+				if [[ ${2// /} =~ ^[[:digit:],-]+$ ]]; then
+					EP_LIST_RANGE=${2// /}
 					shift
 				fi
 				;;
-			-e[[:digit:],-]* | --ep-list=[[:digit:],-]*)
+			-e[[:digit:],-\ ]* | --ep-list=[[:digit:],-\ ]*)
 				EP_LIST=true
 				EP_LIST_RANGE=${1#*=}
+				EP_LIST_RANGE=${EP_LIST_RANGE// /}
 				[[ $EP_LIST_RANGE =~ ^[[:digit:],-]+$ ]]
 				EP_LIST_RANGE=$(echo "$EP_LIST_RANGE" | grep -o . | grep '^[[:digit:],-]*$' | tr -d \\n | sed 's/,$//')
 				;;
@@ -177,11 +177,11 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				PREFFERED_TR=$(echo "$1" | tr -d - | cut -c1 | tr '[:upper:]' '[:lower:]')ub
 				;;
 			-* | --*)
-				echo Invalid option -- $1 1>&2
+				echo "Invalid option -- $1" 1>&2
 				exit 1
 				;;
 			*)
-				SEARCHSTR="$(echo $SEARCHSTR $1 | sed 's|^ *||g;s|* $||g')"
+				SEARCHSTR="$(echo "$SEARCHSTR $1" | sed 's|^ *||g;s|* $||g')"
 				;;
 		esac
 		shift 1
@@ -189,23 +189,23 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 	if [[ -n $TYPE_ANIME ]] && ([[ $TYPE_ANIME = subbed ]] || [[ $TYPE_ANIME = dubbed ]]); then
 		tr=$TYPE_ANIME
 	else
-		tr="$(echo "$@" | sed 's|০|0|g;s|১|1|g;s|২|2|g;s|৩|3|g;s|৪|4|g;s|৫|5|g;s|৬|6|g;s|৭|7|g;s|৮|8|g;s|৯|9|g' | sed 's| |\n|g' | grep -E '^sub$' || echo dub)bed"
+		tr="$(echo "$@" | sed 'y/০১২৩৪৫৬৭৮৯/0123456789/' | sed 's| |\n|g' | grep -E '^sub$' || echo dub)bed"
 	fi
 	if ([[ -n "$EP_LIST_RANGE" ]] || [[ -n "$RES_LIST" ]]) && $DOWNLOAD_ALL; then
 		DOWNLOAD_ALL=false
 		echo -e "Warning: --all/-a option can only be used when no\n\tselection or episode limit specified.\n\tDisabling autodownload mode"
 	fi
-	[[ -n $FORCE ]] && echo ${FORCE} enforced.
+	[[ -n $FORCE ]] && echo "${FORCE} enforced."
 	if [[ $SEARCHSTR != '' ]]; then
-		if [ -n "$NC" ] || check_up_server dubbedanime.net ${RSOLV:-1}; then
-			if [ -n "$EP_LIST_RANGE" ] && ! validate_limit $EP_LIST_RANGE; then
+		if [ -n "$NC" ] || check_up_server dubbedanime.net "${RSOLV:-1}"; then
+			if [ -n "$EP_LIST_RANGE" ] && ! validate_limit "$EP_LIST_RANGE"; then
 				echo "$(
 					tput setaf 1
 					tput dim
 				)Invalid limit:$EP_LIST_RANGE$(tput sgr0)" > /dev/stderr
 				exit 1
 			fi
-			da_search $SEARCHSTR
+			da_search "$SEARCHSTR"
 			exit $?
 		else
 			echo Request timed out
