danime: Refactor and clean up code

diff --git a/danime/13download b/danime/13download
--- a/danime/13download
+++ b/danime/13download
@@ -61,11 +61,6 @@ da_get_episede()
 		total_pw=$5
 		local tr="$tr"
 		IFS=$'\n'
-		case ${1%%/*} in
-			episode | e) episode_type=episode ;;
-			cartoon | c) episode_type=cartoon ;;
-			*) echo ${1%%/*}:invalid ;;
-		esac
 		start_spinner "Fetching info about episode[id:$(echo "${1%%-*}" | xargs basename)]"
 		${DEBUG:-false} && set -x
 		if ! [[ $1 =~ ^http* ]]; then
@@ -119,11 +114,11 @@ da_get_episede()
 				| sed 's/\;$//g;s/^[[:blank:]]*//g' \
 				| head -1
 		)"
-		if echo "$tr" | grep -qvw 'dubbed\|subbed'; then
-			tr=dubbed
+		if echo "$tr" | grep -qvw 'dub\|sub'; then
+			tr=dub
 		fi
-		if [[ $tr = dubbed ]] || [[ $tr = subbed ]]; then
-			filter="grep '\"type\":\"$tr'"
+		if [[ $tr = dub ]] || [[ $tr = sub ]]; then
+			filter="grep '\"type\":\s*\"${tr}\(bed\|\)\"'"
 		else
 			filter="cat"
 		fi
@@ -132,56 +127,54 @@ da_get_episede()
 			echo Episode not available.
 			${NOBREAK:-false} && return 0 || return 1
 		fi
-		if [ "$episode_type" = "episode" ]; then
-			ep_title=$(echo "$parse_episode_page" | jq -r '.name.default')
-			local ep_number
-			ep_number=$(echo "$parse_episode_page" | jq -r '.number')
-			if [ "$ep_number" = "null" ]; then
-				ep_number=$(
-					echo "$parse_episode_page" \
-						| jq -r '.name.default' \
-						| rev \
-						| cut -d' ' -f1 \
-						| rev
-				)
-				if ! [[ $ep_number =~ ^[[:digit:].]+$ ]]; then
-					((null_ep_count += 1))
-					ep_number=${null_ep_count}n
-					# shellcheck disable=SC2001
-					ep_title="$(echo "$ep_title" | sed 's|episode|special|gI') ${ep_number}"
-					export null_ep_count
-				fi
+		ep_title=$(echo "$parse_episode_page" | jq -r '.name.default')
+		local ep_number
+		ep_number=$(echo "$parse_episode_page" | jq -r '.number')
+		if [ "$ep_number" = "null" ]; then
+			ep_number=$(
+				echo "$parse_episode_page" \
+					| jq -r '.name.default' \
+					| rev \
+					| cut -d' ' -f1 \
+					| rev
+			)
+			if ! [[ $ep_number =~ ^[[:digit:].]+$ ]]; then
+				((null_ep_count += 1))
+				ep_number=${null_ep_count}n
+				# shellcheck disable=SC2001
+				ep_title="$(echo "$ep_title" | sed 's|episode|special|gI') ${ep_number}"
+				export null_ep_count
 			fi
-			ep_title=${ep_title% *}
-			if [ "${ep_title% *}" = "${ep_title##* }" ]; then
-				ep_title="$TITLE $ep_title"
-			elif [[ "${ep_title% *}" =~ ${ep_title##* }$ ]]; then
-				ep_title="$(echo "$ep_title" | tr ' ' $'\n' | head -n -1 | xargs echo)"
-			fi
-			ep_title="${ep_title% *} $(echo "${ep_title##* } $ep_number" | sed 's|episode|ep|gI;s|ova|ova|gI;s|ona|ona|gI;s|movie|movie|gI;s|special|special|gI')"
-			ep_title="$(echo "$ep_title" | sed 's| *$||g;s|^ *||g')"
+		fi
+		ep_title=${ep_title% *}
+		if [ "${ep_title% *}" = "${ep_title##* }" ]; then
+			ep_title="$TITLE $ep_title"
+		elif [[ "${ep_title% *}" =~ ${ep_title##* }$ ]]; then
+			ep_title="$(echo "$ep_title" | tr ' ' $'\n' | head -n -1 | xargs echo)"
+		fi
+		ep_title="${ep_title% *} $(echo "${ep_title##* } $ep_number" | sed 's|episode|ep|gI;s|ova|ova|gI;s|ona|ona|gI;s|movie|movie|gI;s|special|special|gI')"
+		ep_title="$(echo "$ep_title" | sed 's| *$||g;s|^ *||g')"
+		slug=$(
+			echo "$parse_episode_page" \
+				| jq -r '.slug' \
+				| sed "s/\(-episode-\)/$([[ ${tr:0:1} == d ]] && echo -${tr:0:3})\1/"
+		)
+		ep_id_list=$(
+			echo "$parse_episode_page" \
+				| da_read_ep_json "$filter" "$slug"
+		)
+		if [ -z "$ep_id_list" ]; then
+			tr=sub
 			slug=$(
 				echo "$parse_episode_page" \
-					| jq -r '.slug' \
-					| sed "s/\(-episode-\)/$([[ ${tr:0:1} == d ]] && echo -${tr:0:3})\1/"
+					| jq -r '.slug'
 			)
-			ep_id_list=$(
-				echo "$parse_episode_page" \
-					| da_read_ep_json "$filter" "$slug"
-			)
-			if [ -z "$ep_id_list" ]; then
-				tr=subbed
-				slug=$(
-					echo "$parse_episode_page" \
-						| jq -r '.slug'
-				)
-				ep_id_list=$(echo "$parse_episode_page" | da_read_ep_json "$filter" "$slug")
-			fi
-			if echo "$1" | grep -q "-extra-[[:digit:]]*-english-subbed$"; then
-				ep_title="${ep_title// ep / extra }"
-			fi
-			ep_file_name="$(echo "$ep_title" | replace_invalid)-$tr.mp4"
+			ep_id_list=$(echo "$parse_episode_page" | da_read_ep_json "$filter" "$slug")
 		fi
+		if echo "$1" | grep -q "-extra-[[:digit:]]*-english-${tr}bed$"; then
+			ep_title="${ep_title// ep / extra }"
+		fi
+		ep_file_name="$(echo "$ep_title" | replace_invalid)-${tr}bed.mp4"
 		ep_id_list="$(
 			echo "$ep_id_list" \
 				| awk -e '!seen[$0]++' \
@@ -231,8 +224,7 @@ da_get_episede()
 				ep_file_url=$(get_mapped "$ep_number")
 			fi
 			for ep_file_url_current in $ep_file_url; do
-				if ! [[ $ep_file_url_current =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]] \
-					&& remote_exist "$ep_file_url_current"; then
+				if remote_exist "$ep_file_url_current"; then
 					continue
 				fi
 				ep_file_url=
@@ -249,16 +241,12 @@ da_get_episede()
 			fi
 			for ep_file_url_current in $ep_file_url; do
 				if [ -n "$file_num" ]; then
-					file_num=$((file_num + 1))
-					if [ "$episode_type" = "cartoon" ]; then
-						ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num.mp4"
-					else
-						ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num-$tr.mp4"
-					fi
+					((file_num++))
+					ep_file_name="$(echo "$ep_title" | replace_invalid)-part$file_num-${tr}bed.mp4"
 				fi
 				ep_file_name="${ep_file_name//---/--}"
 				if ! {
-					[[ $tr = dubbed ]] || [[ $tr = subbed ]]
+					[[ $tr = dub ]] || [[ $tr = sub ]]
 				}; then
 					tr=$(echo "$n" | jq -r '.type')
 				fi
@@ -288,42 +276,75 @@ da_get_episede()
 	fi
 }
 
+download_hls()
+{
+	(
+		set -o pipefail
+		trap 'rm -f "$1.part"' EXIT ABRT QUIT INT
+		duration=$(
+			ffprobe -of compact -show_entries \
+				"format=duration" -i "$2" 2> /dev/null \
+				| cut -d= -f2
+		)
+		ffmpeg -y -progress /dev/stdout \
+			-i "$2" -f mp4 "$1.part" 2> /dev/null \
+			| awk -v "duration=$duration" -F= \
+				'/out_time_ms/ {
+					progress= $2 / (duration * 1000000)
+					cols = 50
+					fill = cols * progress
+					bar = gensub(/ /,"#","g",sprintf("%" fill "s",""))
+					blank = sprintf("%" fill - cols "s","")
+					printf "\r%6.2f%% [%s%s]", progress * 100, bar, blank
+				}
+				END{
+					printf "\n"
+				}' \
+			&& mv "$1.mp4.part" "$1.mp4"
+	)
+}
 download()
 {
 	local s1 s2 ret tried
-	s1=$(
-		curl --disable -kLsIXGET "$2" \
-			| awk \
-				'/^HTTP\/[12.]+ 200/,/^\r$/ {
-					gsub(/\r/,"")
-					if( tolower($1) ~ /^content-length:$/) {
-						print $2
-					}
-				}'
-	)
-	s2=$(stat -Lc%s "$1" 2> /dev/null || echo 0)
-	if ((s1 >= s2)); then
-		until fget "$2" "$1"; do
-			ret=$?
-			if [[ $ret = 10 ]]; then
-				return
-			elif ((tried <= ${MAX_TRY:-5})); then
-				tput cuu 2
-				((tried > 1)) && (
+	if [[ $2 =~ https://[[:alnum:][:punct:]]*/[[:alnum:][:punct:]]*.m3u8[[:alnum:][:punct:]]* ]]; then
+		echo "Downloading '$1'"
+		download_hls "$@"
+		ret=$?
+	else
+		s1=$(
+			curl --disable -kLsIXGET "$2" \
+				| awk \
+					'/^HTTP\/[12.]+ 200/,/^\r$/ {
+						gsub(/\r/,"")
+						if( tolower($1) ~ /^content-length:$/) {
+							print $2
+						}
+					}'
+		)
+		s2=$(stat -Lc%s "$1" 2> /dev/null || echo 0)
+		if ((s1 >= s2)); then
+			until fget "$2" "$1"; do
+				ret=$?
+				if [[ $ret = 10 ]]; then
+					return
+				elif ((tried <= ${MAX_TRY:-5})); then
+					tput cuu 2
+					((tried > 1)) && (
+						tput el1
+						tput el
+						tput cuu1
+					)
 					tput el1
 					tput el
-					tput   cuu1
-				)
-				tput el1
-				tput el
-				((tried += 1))
-				echo "Retrying...[$tried]"
-			else
-				break
-			fi
-		done
-	else
-		echo "Manually downloaded $1[$(byte_hr "$s2")],skipping."
+					((tried += 1))
+					echo "Retrying...[$tried]"
+				else
+					break
+				fi
+			done
+		else
+			echo "Manually downloaded $1[$(byte_hr "$s2")],skipping."
+		fi
 	fi
 	if ((ret == 0)) || [ "$CHECK_FILE" == "false" ]; then
 		da_db set saved "$current_ep"
