CHanges:
  * Added Video mirror selector.
  * Updated episode list extractor.

diff --git a/danime/35footer b/danime/35footer
--- a/danime/35footer
+++ b/danime/35footer
@@ -12,19 +12,19 @@ DEBUG=${DEBUG:-false}
 if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 	while [ -n "$1" ]; do
 		case $1 in
-			-v|--version)
-				if [ "${0##*/}" = "35footer" ];then
-					echo " danime  master-$(git rev-parse HEAD|cut -c 1-6)"
+			-v | --version)
+				if [ "${0##*/}" = "35footer" ]; then
+					echo " danime  master-$(git rev-parse HEAD | cut -c 1-6)"
 				else
-					echo " danime  dist-$(grep '^#VERSION_INFO=' "$0"|cut -d= -f2)"
+					echo " danime  dist-$(grep '^#VERSION_INFO=' "$0" | cut -d= -f2)"
 				fi
 				echo
 				echo
 				da_get_license
 				exit 0
-			;;
-			-l|--license)
-				if [ -e "LICENSE" ] && [ "$(head -1 LICENSE|tr -d '[:blank:]')" = "GNUGENERALPUBLICLICENSE" ];then
+				;;
+			-l | --license)
+				if [ -e "LICENSE" ] && [ "$(head -1 LICENSE | tr -d '[:blank:]')" = "GNUGENERALPUBLICLICENSE" ]; then
 					da_get_license true
 					echo
 					echo "See 'LICENSE' for more details."
@@ -32,13 +32,30 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 					da_get_license
 				fi
 				exit 0
-			;;
-			--break|-b)
+				;;
+			--list-mirror)
+				echo Supported Mirrors
+				echo -e "\t${SUPPORTED_HOSTS//\\|/ }"
+				exit 0
+				;;
+			-m | --mirror)
+				if echo "${SUPPORTED_HOSTS//\\|/$'\n'}" | grep -q "${2//,/\\|}"; then
+					PREFFERED_HOSTS="${2//,/|}"
+				fi
+				shift
+				;;
+			--mirror=[[:alnum:].,]*)
+				tmp="${1##*=}"
+				if echo "${SUPPORTED_HOSTS//\\|/$'\n'}" | grep -q "${tmp//,/\\|}"; then
+					PREFFERED_HOSTS="${tmp//,/|}"
+				fi
+				;;
+			--break | -b)
 				BREAK=true
-			;;
-			--no-break|-nb)
+				;;
+			--no-break | -nb)
 				BREAK=false
-			;;
+				;;
 			-B[[:digit:].]*[kKmM] | --block=[[:digit:].]*[kKmM])
 				BS=${1#*=}
 				[[ $BS =~ ^[[:digit:].]+[[:digit:]kKmM]$ ]] || BS=${1/-B/}
@@ -81,13 +98,13 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				;;
 			-r[fm] | --replace=fail | --replace=manual)
 				REPLACE="$(echo ${1#*=} | tr '[:lower:]' '[:upper:]')"
-				if ! echo $REPLACE|grep -qi 'manual\|fail';then
+				if ! echo $REPLACE | grep -qi 'manual\|fail'; then
 					REPLACE="$(
-						if [ "${1/-r/}" = "m" ];then
+						if [ "${1/-r/}" = "m" ]; then
 							echo manual
 						else
 							echo fail
-						fi|tr '[:lower:]' '[:upper:]'
+						fi | tr '[:lower:]' '[:upper:]'
 					)"
 				fi
 				eval "REPLACE_$REPLACE=true"
@@ -156,8 +173,8 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 			-n | --skip)
 				SKIP_DOWNLOAD=true
 				;;
-			-S|--sub|-D|--dub)
-				PREFFERED_TR=$(echo "$1"|tr -d -|cut -c1 |tr '[:upper:]' '[:lower:]')ub
+			-S | --sub | -D | --dub)
+				PREFFERED_TR=$(echo "$1" | tr -d - | cut -c1 | tr '[:upper:]' '[:lower:]')ub
 				;;
 			-* | --*)
 				echo Invalid option -- $1 1>&2
@@ -206,4 +223,3 @@ else
 	exit 1
 fi
 #end:code
-
